CREATE TABLE IF NOT EXISTS `depot_annonce` (
  `id_depot_annonce` INT NOT NULL AUTO_INCREMENT,
  `id_annonce` INT NOT NULL,
  `id_utilisateur` INT NOT NULL,
  `reference` VARCHAR(30) NOT NULL,
  `adresse` VARCHAR(255) NULL,
  `ville` VARCHAR(120) NULL,
  `quartier` VARCHAR(120) NULL,
  `latitude` DECIMAL(10,8) NULL,
  `longitude` DECIMAL(11,8) NULL,
  `type_annonce` ENUM('Colocation','Location','Appart-hôtel','Résidence étudiante','Chambre pour étudiant') NOT NULL,
  `logement` ENUM('Appartement','Maison','Villa','Cabane','Studio','Chalet','Autre') NOT NULL,
  `nombre_pieces` VARCHAR(10) NOT NULL,
  `surface` INT NULL,
  `commodites` JSON NULL,
  `regles` JSON NULL,
  `email` VARCHAR(255) NOT NULL,
  `telephone_code` VARCHAR(8) NULL DEFAULT '+261',
  `telephone` VARCHAR(40) NULL,
  `message` TEXT NULL,
  `visite_3d` TEXT NULL,
  `boost_service_id` INT NULL,
  `date_creation` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_modification` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_depot_annonce`),
  UNIQUE KEY `uk_depot_annonce_reference` (`reference`),
  UNIQUE KEY `uk_depot_annonce_annonce` (`id_annonce`),
  KEY `idx_depot_annonce_utilisateur` (`id_utilisateur`),
  KEY `idx_depot_annonce_type` (`type_annonce`),
  CONSTRAINT `fk_depot_annonce_annonce` FOREIGN KEY (`id_annonce`) REFERENCES `annonces` (`id_annonce`) ON DELETE CASCADE,
  CONSTRAINT `fk_depot_annonce_utilisateur` FOREIGN KEY (`id_utilisateur`) REFERENCES `utilisateurs` (`id_utilisateur`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `depot_annonce_chambres` (
  `id_depot_chambre` INT NOT NULL AUTO_INCREMENT,
  `id_depot_annonce` INT NOT NULL,
  `disponible_a_partir` DATE NOT NULL,
  `loyer` INT NOT NULL DEFAULT 0,
  `charges` INT NULL,
  `caution` INT NULL,
  `surface` INT NULL,
  `meublee` ENUM('Oui','Partiellement','Non','Rachat') NULL,
  `date_creation` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_depot_chambre`),
  KEY `idx_depot_chambres_depot` (`id_depot_annonce`),
  CONSTRAINT `fk_depot_chambres_depot` FOREIGN KEY (`id_depot_annonce`) REFERENCES `depot_annonce` (`id_depot_annonce`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
